from manim import *
from ipmotion_lib import *

class DarjeelingV3Polished(Scene):
    def construct(self):
        theme = Theme()
        all_elements = Group()

        # ═══ Domains ═══
        wrap = DomainGroup('SoC Integration Wrapper (chip_darjeeling_*)', 8.4, -6.5, 23.5, 18.5, theme.text, stroke=theme.background)
        all_elements.add(wrap)
        ip_bg = DomainGroup('OpenTitan Integrated IP (top_darjeeling)', 8.4, -5.5, 22.5, 14.0, theme.panel_2, stroke=theme.panel_2)
        all_elements.add(ip_bg)
        hi_bg = DomainGroup('Hi-Speed Domain', 4.2, -4.9, 11.6, 11.2, theme.panel, stroke=theme.panel)
        all_elements.add(hi_bg)
        lo_bg = DomainGroup('Low-Speed Domain', 14.4, -4.9, 8.8, 11.2, theme.panel, stroke=theme.panel)
        all_elements.add(lo_bg)

        # ═══ Entities ═══
        ibex = IPBlock('Ibex Core\n(RV32IMCB)', theme, width=5.2, height=2.4, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        ibex.move_to([1.4, -0.7, 0])
        all_elements.add(ibex)
        intr = IPBlock('Interrupt\nController', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        intr.move_to([5.6, 0, 0])
        all_elements.add(intr)
        rom = IPBlock('ROM\nPartitions', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        rom.move_to([8.4, 0, 0])
        all_elements.add(rom)
        msram = IPBlock('Main SRAM', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        msram.move_to([5.6, -1.4, 0])
        all_elements.add(msram)
        mbsram = IPBlock('Shared\nMailbox SRAM', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        mbsram.move_to([8.4, -1.4, 0])
        all_elements.add(mbsram)
        main_xbar = IPBlock('Main TL-UL\nCrossbar', theme, width=10.8, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        main_xbar.move_to([4.2, -2.8, 0])
        all_elements.add(main_xbar)
        otbn = IPBlock('OTBN', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        otbn.move_to([0, -4.2, 0])
        all_elements.add(otbn)
        kmac = IPBlock('KMAC', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        kmac.move_to([2.8, -4.2, 0])
        all_elements.add(kmac)
        edn = IPBlock('EDN 0 / 1', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        edn.move_to([5.6, -4.2, 0])
        all_elements.add(edn)
        csrng = IPBlock('CSRNG', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        csrng.move_to([8.4, -4.2, 0])
        all_elements.add(csrng)
        keymgr = IPBlock('Key Manager', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        keymgr.move_to([0, -5.6, 0])
        all_elements.add(keymgr)
        hmac = IPBlock('HMAC', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        hmac.move_to([2.8, -5.6, 0])
        all_elements.add(hmac)
        aes = IPBlock('AES', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        aes.move_to([5.6, -5.6, 0])
        all_elements.add(aes)
        dbgmod = IPBlock('Debug Module', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        dbgmod.move_to([8.4, -5.6, 0])
        all_elements.add(dbgmod)
        dma = IPBlock('DMA', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        dma.move_to([0, -7.0, 0])
        all_elements.add(dma)
        proxy = IPBlock('SoC Proxy', theme, width=2.4, height=1.4, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        proxy.move_to([2.8, -6.8, 0])
        all_elements.add(proxy)
        mux = MuxBlock(2.8, -7.1, 1.4, 0.3, theme.active, stroke=theme.active)
        all_elements.add(mux)
        base_addr = IPBlock('Base Addr', theme, width=2.2, height=0.4, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        base_addr.move_to([2.8, -7.55, 0])
        all_elements.add(base_addr)
        mbox = IPBlock('9 x Mailboxes', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        mbox.move_to([5.6, -7.0, 0])
        all_elements.add(mbox)
        jtagmb = IPBlock('JTAG Mailbox', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        jtagmb.move_to([8.4, -7.0, 0])
        all_elements.add(jtagmb)
        mbx_xbar = IPBlock('Mbx TL-UL', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        mbx_xbar.move_to([5.6, -8.4, 0])
        all_elements.add(mbx_xbar)
        dbg_xbar = IPBlock('Dbg TL-UL', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        dbg_xbar.move_to([8.4, -8.4, 0])
        all_elements.add(dbg_xbar)
        acc = IPBlock('Access Ctrl', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        acc.move_to([1.4, -9.8, 0])
        all_elements.add(acc)
        racl = IPBlock('RACL Control', theme, width=2.4, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        racl.move_to([5.6, -9.8, 0])
        all_elements.add(racl)
        timers = IPBlock('Timers', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=True)
        timers.move_to([12.0, 0, 0])
        all_elements.add(timers)
        retsram = IPBlock('Retention SRAM', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=False)
        retsram.move_to([12.0, -1.4, 0])
        all_elements.add(retsram)
        alert = IPBlock('Alert Handler', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=False)
        alert.move_to([12.0, -4.2, 0])
        all_elements.add(alert)
        otp = IPBlock('OTP Controller', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=False)
        otp.move_to([12.0, -5.6, 0])
        all_elements.add(otp)
        socdbg = IPBlock('SoC Debug', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=False)
        socdbg.move_to([12.0, -7.0, 0])
        all_elements.add(socdbg)
        lifecycle = IPBlock('Life Cycle', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=False)
        lifecycle.move_to([12.0, -8.4, 0])
        all_elements.add(lifecycle)
        peri_xbar = IPBlock('Peri TL-UL', theme, width=1.6, height=9.4, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=False)
        peri_xbar.move_to([14.4, -4.2, 0])
        all_elements.add(peri_xbar)
        gpio = IPBlock('32bit GPIO', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=False)
        gpio.move_to([16.8, 0, 0])
        all_elements.add(gpio)
        spid = IPBlock('1x SPI Device', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=False)
        spid.move_to([16.8, -1.4, 0])
        all_elements.add(spid)
        spih = IPBlock('1 x SPI Host', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=False)
        spih.move_to([16.8, -2.8, 0])
        all_elements.add(spih)
        uart = IPBlock('1 x UART/I2C', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=False)
        uart.move_to([16.8, -4.2, 0])
        all_elements.add(uart)
        pinmux = IPBlock('Pinmux', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=False)
        pinmux.move_to([16.8, -5.6, 0])
        all_elements.add(pinmux)
        sensor = IPBlock('Sensor Control', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=True)
        sensor.move_to([16.8, -7.0, 0])
        all_elements.add(sensor)
        pwr = IPBlock('Pwr & Clk', theme, width=2.4, height=1.0, fill=theme.muted, stroke=theme.stroke, text_color=theme.text, dotted=False, ind=True)
        pwr.move_to([16.8, -8.4, 0])
        all_elements.add(pwr)
        ctn_xbar = IPBlock('CTN TL-UL', theme, width=10.8, height=1.0, fill=theme.active, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        ctn_xbar.move_to([4.2, -11.2, 0])
        all_elements.add(ctn_xbar)
        padring = IPBlock('Padring', theme, width=7.2, height=1.2, fill=theme.stroke, stroke=theme.stroke, text_color=theme.background, dotted=False, ind=False)
        padring.move_to([14.4, -13.0, 0])
        all_elements.add(padring)

        # ═══ Wires (Static) ═══
        w1 = Wire(ibex, main_xbar, start_edge=DOWN, end_edge=UP, manhattan=True, color=theme.muted)
        all_elements.add(w1)
        w2 = Wire(main_xbar, otbn, start_edge=DOWN, end_edge=UP, manhattan=True, color=theme.muted)
        all_elements.add(w2)
        w_kmac = Wire(main_xbar, kmac, start_edge=DOWN, end_edge=UP, manhattan=True, color=theme.muted)
        all_elements.add(w_kmac)
        w_edn = Wire(main_xbar, edn, start_edge=DOWN, end_edge=UP, manhattan=True, color=theme.muted)
        all_elements.add(w_edn)
        w_csrng = Wire(main_xbar, csrng, start_edge=DOWN, end_edge=UP, manhattan=True, color=theme.muted)
        all_elements.add(w_csrng)
        w_rom = Wire(main_xbar, rom, start_edge=UP, end_edge=DOWN, manhattan=True, color=theme.muted)
        all_elements.add(w_rom)
        w_msram = Wire(main_xbar, msram, start_edge=UP, end_edge=DOWN, manhattan=True, color=theme.muted)
        all_elements.add(w_msram)
        w_keymgr = Wire(keymgr, dma, start_edge=DOWN, end_edge=UP, manhattan=True, color=theme.muted)
        all_elements.add(w_keymgr)
        w_dma_mux = Wire(waypoints=[[1.2, -7.0, 0], [2.8, -7.0, 0], [2.8, -6.95, 0]], color=theme.muted)
        all_elements.add(w_dma_mux)
        w5 = Wire(mux, base_addr, start_edge=DOWN, end_edge=UP, manhattan=True, color=theme.muted)
        all_elements.add(w5)
        w_peri = Wire(main_xbar, peri_xbar, start_edge=RIGHT, end_edge=LEFT, manhattan=True, color=theme.muted)
        all_elements.add(w_peri)
        w_gpio = Wire(peri_xbar, gpio, start_edge=RIGHT, end_edge=LEFT, manhattan=True, color=theme.muted)
        all_elements.add(w_gpio)
        w_spid = Wire(peri_xbar, spid, start_edge=RIGHT, end_edge=LEFT, manhattan=True, color=theme.muted)
        all_elements.add(w_spid)
        w_spih = Wire(peri_xbar, spih, start_edge=RIGHT, end_edge=LEFT, manhattan=True, color=theme.muted)
        all_elements.add(w_spih)
        w_uart = Wire(peri_xbar, uart, start_edge=RIGHT, end_edge=LEFT, manhattan=True, color=theme.muted)
        all_elements.add(w_uart)
        w_pinmux = Wire(peri_xbar, pinmux, start_edge=RIGHT, end_edge=LEFT, manhattan=True, color=theme.muted)
        all_elements.add(w_pinmux)
        w_sensor = Wire(peri_xbar, sensor, start_edge=RIGHT, end_edge=LEFT, manhattan=True, color=theme.muted)
        all_elements.add(w_sensor)
        w_pwr = Wire(peri_xbar, pwr, start_edge=RIGHT, end_edge=LEFT, manhattan=True, color=theme.muted)
        all_elements.add(w_pwr)
        w_timers = Wire(peri_xbar, timers, start_edge=LEFT, end_edge=RIGHT, manhattan=True, color=theme.muted)
        all_elements.add(w_timers)
        w_retsram = Wire(peri_xbar, retsram, start_edge=LEFT, end_edge=RIGHT, manhattan=True, color=theme.muted)
        all_elements.add(w_retsram)
        w_alert = Wire(peri_xbar, alert, start_edge=LEFT, end_edge=RIGHT, manhattan=True, color=theme.muted)
        all_elements.add(w_alert)
        w_otp = Wire(peri_xbar, otp, start_edge=LEFT, end_edge=RIGHT, manhattan=True, color=theme.muted)
        all_elements.add(w_otp)
        w_socdbg = Wire(peri_xbar, socdbg, start_edge=LEFT, end_edge=RIGHT, manhattan=True, color=theme.muted)
        all_elements.add(w_socdbg)
        w_lifecycle = Wire(peri_xbar, lifecycle, start_edge=LEFT, end_edge=RIGHT, manhattan=True, color=theme.muted)
        all_elements.add(w_lifecycle)
        w_acc_ctn = Wire(acc, ctn_xbar, start_edge=DOWN, end_edge=UP, manhattan=True, color=theme.muted)
        all_elements.add(w_acc_ctn)
        w_base_acc = Wire(waypoints=[[2.8, -7.75, 0], [2.8, -9.8, 0], [2.6, -9.8, 0]], color=theme.muted)
        all_elements.add(w_base_acc)

        # ═══ Connections ═══
        req_path = ManhattanRoute([[10.8, -13.0, 0], [-1.8, -13.0, 0], [-1.8, -0.7, 0], [-1.2, -0.7, 0]], theme.error)
        all_elements.add(req_path)

        # ═══ Banner ═══
        banner = Banner("OpenTitan Darjeeling Secure Request", theme)
        # Banner stays outside all_elements so it doesn't scale with the block diagram
        banner.move_to([0, 7.5, 0])

        # ═══ Auto-Scaling ═══
        # Fits the entire topology safely within the frame before animating
        all_elements.scale_to_fit_height(config.frame_height * 0.9)
        all_elements.center()
        # Shift down slightly to make room for banner
        all_elements.shift(DOWN * (config.frame_height * 0.05))

        # ═══ Draw Scene ═══
        self.play(FadeIn(banner))
        self.play(FadeIn(all_elements))
        self.wait(0.5)

        # ═══ Cycle 1 ═══
        self.play(banner.update_text("OpenTitan Secure Request Flow (V3 Polished)", theme))
        self.play(req_path.transfer("SEC_REQ", theme.error, theme))
        self.play(ibex.bg.animate.set_color(theme.error), run_time=0.3)
        self.wait(0.5)

        # ═══ Cycle 2 ═══
        self.play(banner.update_text("Routing through SoC Proxy", theme))
        self.play(ibex.bg.animate.set_color(theme.success), run_time=0.3)
        self.play(acc.bg.animate.set_color(theme.active), run_time=0.3)
        self.wait(0.5)

        self.wait(1)
