"""
Generated by IPMotion Compiler v2
FIFO Backpressure Test
Tests V2 components: FifoGrid, Panels, Gates, Manhattan routing.
Run: manim -pql fifo_backpressure_test.py FifoBackpressureScene
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ipmotion_lib import *


class FifoBackpressureScene(Scene):
    def construct(self):
        theme = Theme()

        # Coordinate bands
        BANNER_Y = 3.78
        DATAPATH_Y = 0.0
        CONTROL_Y = -2.5
        ROUTING_Y = 2.5

        # ═══ Entities ═══
        fsm = Panel("Master FSM", "fsm", theme, rows=[])
        fsm.move_to([-5, CONTROL_Y, 0])
        master = IPBlock("DMA Master", theme, width=2.5, height=1.5)
        master.move_to([-2, DATAPATH_Y, 0])
        fifo = FifoGrid("Write Data FIFO", 1, 3, theme)
        fifo.move_to([3, DATAPATH_Y, 0])
        bus_gate = Gate([0.5, ROUTING_Y, 0], theme)

        # ═══ Connections ═══
        fsm_to_master = ManhattanRoute([[-3.6, -2.5, 0], [-2, -2.5, 0], [-2, -0.75, 0]], theme.stroke)
        write_bus = BusRoute(master.get_top(), fifo.get_top(), theme.active, ROUTING_Y)

        # ═══ Banner ═══
        banner = Banner("FIFO Backpressure Test", theme)
        banner.move_to([0, BANNER_Y, 0])

        # ═══ Draw Scene ═══
        self.play(FadeIn(banner, fsm, master, fifo, bus_gate, fsm_to_master, write_bus))
        self.wait(0.5)

        # ═══ Cycle 1 ═══
        self.play(banner.update_text("Cycle 1: Master FSM in IDLE. FIFO is empty.", theme, theme.stroke))
        self.play(fsm.update_fsm("IDLE", theme, theme.stroke))
        self.wait(0.5)

        # ═══ Cycle 2 ═══
        self.play(banner.update_text("Cycle 2: FSM enters WRITE state. Sends WDATA to FIFO.", theme, theme.active))
        self.play(fsm.update_fsm("WRITE", theme, theme.active))
        self.play(fsm_to_master.transfer("START", theme.active, theme))
        self.play(write_bus.transfer("WDATA_0", theme.active, theme))
        self.play(fifo.refresh(0, 0, "0xAA", theme, theme.active))
        self.wait(0.5)

        # ═══ Cycle 3 ═══
        self.play(banner.update_text("Cycle 3: FIFO asserts backpressure (Gate). Master stalls.", theme, theme.warning))
        self.play(bus_gate.assert_gate())
        self.play(fsm.update_fsm("STALL", theme, theme.warning))
        self.play(master.box.animate.set_stroke(theme.warning))
        self.wait(0.5)

        # ═══ Cycle 4 ═══
        self.play(banner.update_text("Cycle 4: FIFO pops data. Gate clears, write completes.", theme, theme.success))
        self.play(fifo.refresh(0, 0, "-", theme, theme.stroke))
        self.play(bus_gate.clear_gate())
        self.play(fsm.update_fsm("IDLE", theme, theme.stroke))
        self.play(master.box.animate.set_stroke(theme.stroke))
        self.wait(0.5)

        self.wait(1)
